### ISSUE TITLE
ValueError: ZeroShotAgent does not support multi-input tool Calculator.

### ISSUE THREAD

**Issue by BankNatchapol** [hwchase17/langchain#3700] opened 2023-04-28 09:33 UTC
There is an error when i tried to use this code.
```
tools = load_tools(['llm-math', 'python_repl'], llm)
agent = initialize_agent(tools, agent="zero-shot-react-description", llm=llm)
```
Looks like because of #3684 checking if len(self.args) == 1: in self.is_single_input. 
But, self.args of llm-math is 
```
{'args': {'title': 'Args', 'type': 'array', 'items': {}},
 'kwargs': {'title': 'Kwargs', 'type': 'object'}}
```
So, self.is_single_input return False

Is there a way to get single input llm-math?

**Comment by Buckler89** [comment] 2023-04-28 09:51
I've had the same problem with all agent types. The _validate_tools method is the problem. Commenting out this line, the agent resumes work:
https://github.com/hwchase17/langchain/blob/v0.0.152/langchain/agents/agent.py#L478

I still can't figure out why.
Does anyone know why the agent shouldn't support a multiple input tool?

I tried with ConversationalAgent with a RetrivalQA tool that needs {context} and {quary} inputs.

**Comment by Pouyanpi** [comment] 2023-04-28 11:49
Hi @BankNatchapol 

I think its related to the recent releases.

Installing v0.0.147 would resolve the issue. Do the following

```bash
pip install --force-reinstall -v langchain==v0.0.147
```

In the meantime someone needs to fix this bug.

**Comment by philipk19238** [comment] 2023-04-29 21:19
I created a PR [here](https://github.com/hwchase17/langchain/pull/3803) that removes the restrictive checking of multi-input in the Agent base class. Will need reviewers to +1 and merge.

**Comment by vowelparrot** [comment] 2023-05-01 01:56
Fixed in 0.0.153

**Closed by vowelparrot** 2023-05-01 01:56 UTC

**Comment by jasgeo75** [comment] 2023-05-01 04:36
> Fixed in 0.0.153

I get the same error with ConversationalChatAgent.  Is this by design or has it only been fixed in ZeroShotAgent?

`ValueError: ConversationalChatAgent does not support multi-input tool query_webpage.`

**Comment by ryanshrott** [comment] 2023-05-01 18:03
getting similar error. Here is a minimal example following their playwright example:

Error:
Traceback (most recent call last):
  File "c:\Users\ryans\Documents\JobsGPT\test.py", line 38, in <module>
    agent = initialize_agent(
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\ryans\.conda\envs\jobsgpt\Lib\site-packages\langchain\agents\initialize.py", line 52, in initialize_agent
    agent_obj = agent_cls.from_llm_and_tools(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryans\.conda\envs\jobsgpt\Lib\site-packages\langchain\agents\mrkl\base.py", line 101, in from_llm_and_tools        
    cls._validate_tools(tools)
  File "C:\Users\ryans\.conda\envs\jobsgpt\Lib\site-packages\langchain\agents\mrkl\base.py", line 125, in _validate_tools
    super()._validate_tools(tools)
  File "C:\Users\ryans\.conda\envs\jobsgpt\Lib\site-packages\langchain\agents\agent.py", line 502, in _validate_tools
    raise ValueError(
ValueError: ZeroShotAgent does not support multi-input tool previous_webpage.

CODE:
`from langchain.agents.agent_toolkits import PlayWrightBrowserToolkit
from langchain.chains.conversation.memory import ConversationBufferWindowMemory
from langchain.tools.playwright.utils import (
    create_async_playwright_browser,
    create_sync_playwright_browser,# A synchronous browser is available, though it isn't compatible with jupyter.
)
from langchain.chat_models import ChatOpenAI
import os
OPENAI_API_KEY=""
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
async_browser = create_async_playwright_browser()
toolkit = PlayWrightBrowserToolkit.from_browser(async_browser=async_browser)

tools = toolkit.get_tools()

tools_by_name = {tool.name: tool for tool in tools}
navigate_tool = tools_by_name["navigate_browser"]
get_elements_tool = tools_by_name["get_elements"]

print(tools)

# conversational agent memory
memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=3,
    return_messages=True
)

from langchain.agents import initialize_agent
# Set up the turbo LLM
turbo_llm = ChatOpenAI(
    temperature=0,
    model_name='gpt-3.5-turbo'
)
from langchain.agents import AgentType

# create our agent
agent = initialize_agent(
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    tools=tools,
    llm=turbo_llm,
    verbose=True,
)

out = agent.run("Is there an article about Clubhouse on https://techcrunch.com/? today")

print(out)`

**Comment by vowelparrot** [comment] 2023-05-01 21:45
Yes the playwright and other structured tools will be compatible with a new agent. Previous agents' format instructions and parsers don't work well with more complex signatures

**Comment by ryanshrott** [comment] 2023-05-01 21:50
> Yes the playwright and other structured tools will be compatible with a new agent. Previous agents' format instructions and parsers don't work well with more complex signatures

Ok so which agent should I use then? Any examples?

**Comment by tirthb** [comment] 2023-05-09 21:26
Seeing the same error as @jasgeo75 for `ValueError: ConversationalChatAgent does not support multi-input tool`

Any workaround other than downgrading langchain?

**Comment by vowelparrot** [comment] 2023-05-09 21:36
@tirthb  for the `llm-math` / `python-repl` tool or something else? This particular issue was resolved for these tools.

For newer tools (playwright, write file, etc.), they are only compatible with newer agents.

**Comment by tirthb** [comment] 2023-05-09 21:53
Thanks, I was writing a custom tool that takes multiple arguments and calls an API. What am I doing wrong?

```
class OrgSearchTool(BaseTool):
    name = "Get Organization Details"
    description = "Useful when searching for information about an organization or company for a give name and website."

    def _run(self, name: str, website: str):
        from api import search_org
        r = search_org(name, website)
        if len(r) > 4000:
            r = r[:4000]
        return r
    
    def _arun(self, webpage: str):
        raise NotImplementedError("This tool does not support async")

org_search = OrgSearchTool()

tools = [search, org_search]
```

**Comment by vowelparrot** [comment] 2023-05-09 22:32
That should be correct, it's just not compatible with the ZeroShotAgent. You could try the `AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION` or the autogpt agent or write your own agent though

**Comment by tirthb** [comment] 2023-05-09 23:32
Thanks for your help. It is not working as expected with AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION

As it does not use my API even when I prompt it otherwise by modifying the template.

I have downgraded langchain to v0.0.147 for now.

**Comment by okonma01** [comment] 2023-05-12 15:19
I am still getting an error when I try to use agents.

The code I run is from the langchain Quickstart Guide [(Agents)](https://python.langchain.com/en/latest/getting_started/getting_started.html#agents-dynamically-call-chains-based-on-user-input)

`from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.agents import AgentType
from langchain.llms import OpenAI

# First, let's load the language model we're going to use to control the agent.
llm = OpenAI(temperature=0)

# Next, let's load some tools to use. Note that the `llm-math` tool uses an LLM, so we need to pass that in.
tools = load_tools(["serpapi", "llm-math"], llm=llm)


# Finally, let's initialize an agent with the tools, the language model, and the type of agent we want to use.
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

# Now let's test it out!
agent.run("What was the high temperature in SF yesterday in Fahrenheit? What is that number raised to the .023 power?")`

And then I get the following error:

`ValueError                                Traceback (most recent call last)
Cell In[48], line 11
      7 tools = load_tools(["serpapi", "llm-math"], llm=llm)
     10 # Finally, let's initialize an agent with the tools, the language model, and the type of agent we want to use.
---> 11 agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
     13 # print(tools)
     14 
     15 # Now let's test it out!
     16 # agent.run("What was the lowest temperature in Mississauga yesterday in Celsius? What is that number squared")

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/initialize.py:52, in initialize_agent(tools, llm, agent, callback_manager, agent_path, agent_kwargs, **kwargs)
     50     agent_cls = AGENT_TO_CLASS[agent]
     51     agent_kwargs = agent_kwargs or {}
---> 52     agent_obj = agent_cls.from_llm_and_tools(
     53         llm, tools, callback_manager=callback_manager, **agent_kwargs
     54     )
     55 elif agent_path is not None:
     56     agent_obj = load_agent(
     57         agent_path, llm=llm, tools=tools, callback_manager=callback_manager
     58     )

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/mrkl/base.py:101, in ZeroShotAgent.from_llm_and_tools(cls, llm, tools, callback_manager, output_parser, prefix, suffix, format_instructions, input_variables, **kwargs)
     87 @classmethod
     88 def from_llm_and_tools(
     89     cls,
   (...)
     98     **kwargs: Any,
     99 ) -> Agent:
    100     """Construct an agent from an LLM and tools."""
--> 101     cls._validate_tools(tools)
    102     prompt = cls.create_prompt(
    103         tools,
    104         prefix=prefix,
   (...)
    107         input_variables=input_variables,
    108     )
    109     llm_chain = LLMChain(
    110         llm=llm,
    111         prompt=prompt,
    112         callback_manager=callback_manager,
    113     )

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/mrkl/base.py:125, in ZeroShotAgent._validate_tools(cls, tools)
    123 @classmethod
    124 def _validate_tools(cls, tools: Sequence[BaseTool]) -> None:
--> 125     super()._validate_tools(tools)
    126     for tool in tools:
    127         if tool.description is None:

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/agents/agent.py:459, in Agent._validate_tools(cls, tools)
    457 for tool in tools:
    458     if not tool.is_single_input:
--> 459         raise ValueError(
    460             f"{cls.__name__} does not support multi-input tool {tool.name}."
    461         )

ValueError: ZeroShotAgent does not support multi-input tool Calculator.`

I tried downgrading to the older version @Pouyanpi mentioned; it still didn't work. 

I checked the history release of the repo, and I did not see any release that fixed this specific issue (#3700)

Did anyone figure this out yet?

**Comment by not-apollo** [comment] 2023-05-15 20:36
Just so I'm clear, there's no way to use an agent right now that can use both multiinput and single-input tools right? It has to be all one or the other?

**Comment by medram** [comment] 2023-05-26 18:39
Having the same issue, any solution without downgrading?

**Comment by lalligagger** [comment] 2023-05-27 13:02
Same issue as @tirthb described for me, 0.0.147 downgrade seems to work.

**Comment by vowelparrot** [comment] 2023-05-28 22:24
> Just so I'm clear, there's no way to use an agent right now that can use both multiinput and single-input tools right? It has to be all one or the other?

All agents can use single input tools. Only newer agents can use multi-input tools right now

**Comment by vowelparrot** [comment] 2023-05-28 22:26
@okonma01 could you share your version info for this package?

**Comment by lalligagger** [comment] 2023-05-28 22:27
Looking at the new StructuredTool docs helped me, if anyone hasn't seen those yet. I am moving my tools to use that class, which has worked well so far.

**Comment by jpzhangvincent** [comment] 2023-06-03 17:15
Same question here, how do you use the structured tool to wrap the ConversationalChatAgent so that it can also be passed with the `chat_history`?

**Comment by rogerbock** [comment] 2023-06-27 16:54
Got it. As a new user, it was not immediately clear which agents were the right ones to use. Maybe the old ones should print a deprecation warning if they are used?

**Comment by ramnes** [comment] 2023-07-11 09:12
As a LangChain newcomer, I just got hit by this one as well.

The tools documentation shows examples of multi-input tools without mentioning agent types ([e.g. here](https://python.langchain.com/docs/modules/agents/tools/how_to/custom_tools#using-the-decorator)).

Maybe the default agent used in `initialize_agent` should be changed, so that it uses `AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION` instead? If so, happy to make the PR.

**Comment by astelmach01** [comment] 2023-09-09 01:04
as @tirthb 

> I am seeing this issue in the latest version (langchain==0.0.216). Why was this issue closed?
> 
> ```
> >>> agent = initialize_agent(tools, chat_llm, agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/rb013z/venvs/hackathon39/lib/python3.9/site-packages/langchain/agents/initialize.py", line 57, in initialize_agent
>     agent_obj = agent_cls.from_llm_and_tools(
>   File "/Users/rb013z/venvs/hackathon39/lib/python3.9/site-packages/langchain/agents/chat/base.py", line 112, in from_llm_and_tools
>     cls._validate_tools(tools)
>   File "/Users/rb013z/venvs/hackathon39/lib/python3.9/site-packages/langchain/agents/chat/base.py", line 62, in _validate_tools
>     validate_tools_single_input(class_name=cls.__name__, tools=tools)
>   File "/Users/rb013z/venvs/hackathon39/lib/python3.9/site-packages/langchain/agents/utils.py", line 10, in validate_tools_single_input
>     raise ValueError(
> ValueError: ChatAgent does not support multi-input tool calculate_discount.
> ```
> 
> EDIT: It looks like using a different AgentType works. `agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION`

As @tirthb mentioned, zero shot has no memory. "chat-conversational-react-description" needs to have support for multi input tools.

**Comment by zeratulus** [comment] 2025-08-20 13:42
I solve this problem: "ZeroShotAgent does not support multi-input tool get_repository_status." in my code just with changing of:
AgentType.ZERO_SHOT_REACT_DESCRIPTION 
to: 
AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION

on initialization of agent:

agent = initialize_agent(
    tools,
    llm,
    agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True
)

With best regards.
