### ISSUE TITLE
Support pydantic v2

### ISSUE THREAD

**Issue by gyroflaw** [hwchase17/langchain#8058] opened 2023-07-21 07:13 UTC
### Feature request

Please support pydantic v2 version.

### Motivation

Pydantic v2 [released](https://docs.pydantic.dev/latest/blog/pydantic-v2-final/) a few weeks ago with [a lot of features](https://docs.pydantic.dev/latest/blog/pydantic-v2/#performance) shipped.

> Looking at the pydantic-core [benchmarks](https://github.com/pydantic/pydantic-core/tree/main/tests/benchmarks) today, 
> pydantic V2 is between 4x and 50x faster than pydantic V1.9.1.
> In general, pydantic V2 is about 17x faster than V1 when validating a model containing a range of common fields.

### Your contribution

Let me know if you allow contribution to this then will try to work on this.

**Comment by devstein** [comment] 2023-07-21 14:16
Duplicate of #6841

**Closed** 2023-07-21 14:19 UTC
Labels: auto:improvement
