### ISSUE TITLE
Support HuggingFaceHub embeddings endpoint

### ISSUE THREAD

**Issue by delip** [hwchase17/langchain#136] opened 2022-11-14 16:32 UTC
The current implementation of `HuggingFaceEmbeddings` local sentence-transformers to derive the encodings. This can be limiting as it requires a fairly capable machine to download the model, load it, and run inference.

An alternative is to support embeddings derived directly via the HuggingFaceHub. See this [blog post](https://huggingface.co/blog/getting-started-with-embeddings) for details. This implementation will set similar expectations as Cohere and OpenAI embeddings API.

**Comment by hwchase17** [comment] 2022-11-14 16:35
i think this is a duplicate of #86 (with pr #125 )?

**Closed** 2022-11-14 16:41 UTC
